name = "examples"
version = "1.0.0"

# Fill out these fields if you intend to generate HTML documentation or publish
# your project to the Hex package manager.
#
# description = ""
# licences = ["Apache-2.0"]
# repository = { type = "github", user = "username", repo = "project" }
# links = [{ title = "Website", href = "https://gleam.run" }]

[dependencies]
gleam_stdlib = "~> 0.34 or ~> 1.0"
teashop = { path = ".." }
shellout = "~> 1.5"
gleam_javascript = "~> 0.7"

[dev-dependencies]
gleeunit = "~> 1.0"
